### ISSUE TITLE
Minus prevents loading when using modded dungeons.

### ISSUE THREAD

**Issue by BlueYoshi68** [Sylkadi/Brutal_Company_Minus#2]
Specifically this dungeon (so far) https://thunderstore.io/c/lethal-company/p/Major_And_Skiz/MoreInteriors/
just get's stuck at displaying the level seed and never actually finishes loading.

[LogOutput.log](https://github.com/Sylkadi/Brutal_Company_Minus/files/14002180/LogOutput.log)

Edit: Seems to be the case for ALL interiors, as I also tried with the other popular interior mod https://thunderstore.io/c/lethal-company/p/scoopy/Scoopys_Variety_Mod/

[LogOutput2.log](https://github.com/Sylkadi/Brutal_Company_Minus/files/14002211/LogOutput2.log)

This error was present in the first one:
`[Error  : Unity Log] ArgumentException: The Object you want to instantiate is null.
Stack trace:
UnityEngine.Object.Instantiate (UnityEngine.Object original, UnityEngine.Vector3 position, UnityEngine.Quaternion rotation) (at <e27997765c1848b09d8073e5d642717a>:IL_0049)
UnityEngine.Object.Instantiate[T] (T original, UnityEngine.Vector3 position, UnityEngine.Quaternion rotation) (at <e27997765c1848b09d8073e5d642717a>:IL_0001)
Brutal_Company_Minus._Event.Manager.DoSpawnInsideEnemies () (at <76f52590d6c647549e21ea2dd629fc92>:IL_0095)
Brutal_Company_Minus.Patches.RoundManagerPatch.OnRefreshEnemyVents () (at <76f52590d6c647549e21ea2dd629fc92>:IL_000D)
(wrapper dynamic-method) RoundManager.DMD<RoundManager::RefreshEnemyVents>(RoundManager)
RoundManager+<LoadNewLevelWait>d__115.MoveNext () (at <af9b1eec498a45aebd42601d6ab85015>:IL_016B)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:IL_0026)`

While this error was present in the 2nd one:
`[Error  : Unity Log] ArgumentException: The Object you want to instantiate is null.
Stack trace:
UnityEngine.Object.Instantiate (UnityEngine.Object original, UnityEngine.Vector3 position, UnityEngine.Quaternion rotation) (at <e27997765c1848b09d8073e5d642717a>:IL_0049)
UnityEngine.Object.Instantiate (UnityEngine.Object original, UnityEngine.Vector3 position, UnityEngine.Quaternion rotation, UnityEngine.Transform parent) (at <e27997765c1848b09d8073e5d642717a>:IL_000C)
UnityEngine.Object.Instantiate[T] (T original, UnityEngine.Vector3 position, UnityEngine.Quaternion rotation, UnityEngine.Transform parent) (at <e27997765c1848b09d8073e5d642717a>:IL_0001)
(wrapper dynamic-method) RoundManager.DMD<RoundManager::SpawnScrapInLevel>(RoundManager)
(wrapper dynamic-method) RoundManager.DMD<RoundManager::GeneratedFloorPostProcessing>(RoundManager)
RoundManager+<LoadNewLevelWait>d__115.MoveNext () (at <af9b1eec498a45aebd42601d6ab85015>:IL_013C)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:IL_0026)`

Really hoping this is fixed eventually, because this mod (in terms of features) seems alot more interesting than Plus, but plus works, so I dont really have a choice.

**Comment by Sylkadi** [comment]
The culprit is the newest version of Atlas Abyss v.1.1.3 by Zingar, if you want to use my mod downgrade Atlas_Abyss to v1.1.2.
For whatever reason this release straight up removes a bunch of prefabs????
I don't know why. I hope i'm right.
![Screenshot_108](https://github.com/Sylkadi/Brutal_Company_Minus/assets/101504347/2d77f867-7f17-487d-a113-0c3e77905b4b)

**Comment by BlueYoshi68** [comment]
WHat about the other generator?

**Comment by BlueYoshi68** [comment]
-Update. Bugs out and does the same Seed generation bug on Etern https://thunderstore.io/c/lethal-company/p/Magic_Wesley/Etern/

**Comment by Sylkadi** [comment]
I wasn't able to reproduce with Etern, but same thing happend with SecrebLabs v3.3.3 by Zingar but downgrading it to v.3.3.2 fixed it for me. I don't know what he did, but when i get back home from work i'll try to get a fix.

**Comment by BlueYoshi68** [comment]
You had it on SL???
That's extremely strange, cause I did not and im on 3.3.3???

This mod is extremely inconsistent....or something

**Comment by BlueYoshi68** [comment]
It seems to also consistently happen when ever I get the 'dentures' modifier

**Comment by Sylkadi** [comment]
Should be more stable in latest release, though not fully fixed.
