### ISSUE TITLE
[Suggestion] Add an option to completely remove/hide new UI from v0.6.0+ versions

### ISSUE THREAD

**Issue by NilaierMusic** [Sylkadi/Brutal_Company_Minus#4]
There's a way to unbind the new UI button, but you can't prevent it from showing up when you land on the moon. Would be great to have a config option to completely remove/hide the UI or at least choose an information that shows up with it.
![notepad++_sHWAXzWNsu](https://github.com/Sylkadi/Brutal_Company_Minus/assets/86863646/870e6e34-cd6d-463e-8b5a-bad40940f32d)

**Comment by Sylkadi** [comment]
Will do in next patch.

**Comment by RamennBowls** [comment]
I don't mean to re-open this issue, but could you also add an option to bring back the original messages into the chat (prior to the UI update)?

**Comment by RamennBowls** [comment]
@Sylkadi Would it be possible to add an option that puts the events into the chat as it did before, prior to the UI update?
