### ISSUE TITLE
Weight not effective

### ISSUE THREAD

**Issue by MarionetteYL** [Sylkadi/Brutal_Company_Minus#5]
When I don't want an event to happen, I set the weight of that event to 0, like this:
```
[Pickles]

# Setting type: Int32
# Default value: 2
Weight = 0 

# Setting type: String
# Default value: Tastes salty...
Description =Tastes salty...

```
But when I enter the game, this event still appears,how can I solve this problem.

**Comment by BlueYoshi68** [comment]
![image](https://github.com/Sylkadi/Brutal_Company_Minus/assets/10472980/f303c57c-5038-4e1c-8420-7d61e6572bfe)

**Comment by Sylkadi** [comment]
Added option to disable an event outright. And made it more clear in the config about weights.
